version: "3"
services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"