"""Add occupation

Revision ID: 03b22e21617f
Revises: 2d34f8e053c0
Create Date: 2024-09-14 15:43:47.098906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b22e21617f'
down_revision: Union[str, None] = '2d34f8e053c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'occupation')
    # ### end Alembic commands ###
