"""change guided journal body type

Revision ID: 9a8fe4bb9b95
Revises: 03b22e21617f
Create Date: 2024-09-15 14:26:28.714654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8fe4bb9b95'
down_revision: Union[str, None] = '03b22e21617f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guided_journal_entries', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="body::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guided_journal_entries', 'body',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="body::text")
    # ### end Alembic commands ###
