"""therapist user id

Revision ID: 9dd69f8ce332
Revises: d0a4a18e401a
Create Date: 2024-10-06 14:53:12.647639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd69f8ce332'
down_revision: Union[str, None] = 'd0a4a18e401a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_data', sa.Column('therapist_user_id', sa.Integer(), nullable=True))
    
    op.execute("""
        UPDATE patient_data
        SET therapist_user_id = (
            SELECT td.user_id
            FROM therapist_data td
            WHERE td.id = patient_data.therapist_id
        )
        WHERE therapist_id IS NOT NULL
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_data', 'therapist_user_id')
    # ### end Alembic commands ###
