"""add fields in mood entry

Revision ID: bffd47c6cee0
Revises: 9a8fe4bb9b95
Create Date: 2024-09-15 19:31:28.430829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffd47c6cee0'
down_revision: Union[str, None] = '9a8fe4bb9b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('eat', sa.SmallInteger(), nullable=True))
    op.add_column('mood_entries', sa.Column('sleep', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_entries', 'sleep')
    op.drop_column('mood_entries', 'eat')
    # ### end Alembic commands ###
