"""Add streak

Revision ID: e4ed14eff776
Revises: 5fb9083bb7a6
Create Date: 2024-10-06 15:27:37.446832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ed14eff776'
down_revision: Union[str, None] = '5fb9083bb7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streak')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
